### ISSUE TITLE
Panic when calling Destroy() on client

### ISSUE THREAD

**Issue by samjbobb** [splitio/go-client#81]
Hi – I have the Split SDK working in my Go app. Setup and getting treatments for features is working. 

I just implemented shutdown as described here: https://help.split.io/hc/en-us/articles/360020093652-Go-SDK#shutdown

I get a panic on calling `Destroy()`. Here's a minimal test case that reproduces the issue:

```
import (
	"fmt"
	"github.com/splitio/go-client/splitio/client"
	"github.com/splitio/go-client/splitio/conf"
	"github.com/splitio/go-toolkit/logging"
	"testing"
)

func TestSplitCreateAndDestroy(t *testing.T) {
	// Boot
	cfg := conf.Default()
	cfg.BlockUntilReady = 10
	cfg.LoggerConfig.LogLevel = logging.LevelDebug
	factory, err := client.NewSplitFactory("<MY_API_KEY>", cfg)
	if err != nil {
		t.Fatal("SDK init error: %s\n", err)
		return
	}
	c := factory.Client()

	// Get treatment
	treatment := c.Treatment("user-id", "myfeature", nil)
	fmt.Println("Treatment is", treatment)

	// Panics
	c.Destroy()

}
```

Output:

```
=== RUN   TestSplit
INFO - 2019/05/16 [Sdk initialization complete!]
DEBUG - 2019/05/16 [[GET]  https://sdk.split.io/api/splitChanges?since=-1]
WARNING - 2019/05/16 [Feature myfeature not found, returning control.]
Treatment is control
DEBUG - 2019/05/16 [Authorization [ApiKey]:  <omitted>]
--- FAIL: TestSplit (0.31s)
DEBUG - 2019/05/16 [Headers: map[Accept-Encoding:[gzip] Content-Type:[application/json] Splitsdkversion:[4.0.0]]]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1330ad4]

goroutine 34 [running]:
testing.tRunner.func1(0xc000116100)
	/usr/local/go/src/testing/testing.go:830 +0x392
panic(0x1390880, 0x1727520)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/splitio/go-client/splitio/client.(*SplitClient).Destroy(0xc0000d2120)
	/Users/sam/go/pkg/mod/github.com/splitio/go-client@v0.0.0-20190430211721-3404cfbfbdff/splitio/client/client.go:292 +0xc4
github.com/octopart/highfive/split.TestSplit(0xc000116100)
	/Users/sam/octopart/frontend/highfive/split/split_test.go:28 +0x210
testing.tRunner(0xc000116100, 0x141b9e0)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a

Process finished with exit code 1
```

Versions and environment and stuff:

OS X 10.13.6

```
$ go version
go version go1.12.5 darwin/amd64
```

```
$ grep split go.mod 
        github.com/splitio/go-client v0.0.0-20190430211721-3404cfbfbdff
        github.com/splitio/go-toolkit v0.0.0-20190325151430-51a1aa930e99
```

Thanks!

**Comment by mredolatti** [comment]
Hello @samjbobb, thank you for reporting this issue. We are sorry for any inconveniences caused.
We already have a fix which is being tested in our QoS environment and will be released later today. We will let you know immediately when that happens.

Thank you very much for your patience.
Martin.

**Comment by mredolatti** [comment]
Hi @samjbobb go-client 4.0.1 is out and should fix the problem you reported.
Please let us know if you have any further issues or questions regarding our SDK.

I'll be closing this issue for now, but feel free to reopen if necessary.

Thank you once again for reaching out.
Martin.

**Comment by samjbobb** [comment]
Thanks for the quick fix. Will try it out.
